const { v4: uuidv4 } = require('uuid');

/**
 * VENDING SERVICE
 * 
 * NOTE: This is a SIMULATION for development/testing.
 * In production, replace the simulateVending method with real API calls
 * to VTpass, BuyPower, or your DISCO's direct API.
 * 
 * Real implementation would look like:
 * 
 * async vendToken({ meterNumber, amount, disco }) {
 *   const response = await fetch(`${process.env.VENDING_BASE_URL}/pay`, {
 *     method: 'POST',
 *     headers: {
 *       'Authorization': `Basic ${Buffer.from(`${key}:${secret}`).toString('base64')}`,
 *       'Content-Type': 'application/json'
 *     },
 *     body: JSON.stringify({
 *       request_id: `KEDCO_${Date.now()}`,
 *       serviceID: 'kaduna-electric',
 *       billersCode: meterNumber,
 *       variation_code: 'prepaid',
 *       amount: amount,
 *       phone: customerPhone
 *     })
 *   });
 *   return await response.json();
 * }
 */

class VendingService {
  /**
   * Simulate a token vending response
   * In production, this calls the actual vending API
   */
  async vendToken({ meterNumber, amount, phone }) {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 1500));

    // Generate a realistic 20-digit STS token
    // Real tokens are cryptographically generated by the DISCO
    const token = this.generateSimulatedToken();

    // Calculate approximate units (Nigeria: ~₦55-65 per kWh for residential)
    // This is approximate and varies by tariff band
    const tariffRate = 58.5; // Naira per kWh
    const units = parseFloat((amount / tariffRate).toFixed(2));

    return {
      success: true,
      token,
      units,
      amount,
      meterNumber,
      transactionId: `KEDCO-${uuidv4().split('-')[0].toUpperCase()}`,
      timestamp: new Date().toISOString(),
      // In real implementation, this would be the raw API response
      rawResponse: {
        status: 'success',
        code: '000',
        description: 'Transaction Successful'
      }
    };
  }

  /**
   * Validate meter number with DISCO
   * In production, this calls the actual validation API
   */
  async validateMeter(meterNumber) {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 800));

    // Basic validation: Kaduna Electric prepaid meters are typically 11-15 digits
    const isValidFormat = /^\d{11,15}$/.test(meterNumber);

    if (!isValidFormat) {
      return {
        valid: false,
        message: 'Invalid meter number format. Kaduna Electric meters are 11-15 digits.'
      };
    }

    // Simulate validation response
    // In production, this comes from the DISCO API
    return {
      valid: true,
      meterNumber,
      customerName: `Customer ${meterNumber.slice(-4)}`,
      customerAddress: 'Kaduna, Nigeria',
      disco: 'Kaduna Electric',
      meterType: 'prepaid',
      tariffBand: 'Band A',
      status: 'active'
    };
  }

  generateSimulatedToken() {
    // Generate a 20-digit number that looks like an STS token
    // Format: XXXX XXXX XXXX XXXX XXXX (groups of 4)
    let token = '';
    for (let i = 0; i < 5; i++) {
      token += Math.floor(1000 + Math.random() * 9000).toString();
    }
    return token;
  }
}

module.exports = new VendingService();
